ARG CADDY_VERSION="2"
FROM caddy:${CADDY_VERSION}-builder-bookworm AS builder
ARG TARGETARCH

RUN xcaddy build --with github.com/caddy-dns/cloudflare

FROM caddy:${CADDY_VERSION}-bookworm
ARG TARGETARCH

COPY --from=builder /usr/bin/caddy /usr/bin/caddy