name: "Build and push Caddy"

on:
  workflow_dispatch:
    inputs:
      caddy_version:
        description: "Caddy version"
        default: "2"
        required: true

jobs:
  build_http_server:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        variant:
          - alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push - ${{ matrix.variant }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile-${{ matrix.variant }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CADDY_VERSION=${{ github.event.inputs.caddy_version }}
          tags: |
            phillarmonic/caddy-cloudflare:${{ github.event.inputs.caddy_version }}-${{ matrix.variant }}
